pub use crate::bot::server::{read_config, run_server};

mod session;
mod protocol;
mod server;
mod math;
mod vec2;
mod map;
mod world;
mod bot;
mod walk_grid;
mod clusterization;
mod player;
mod objects;
mod stuck_detector;
mod explorer;
mod exp_wnd_closer;
mod new_character;
mod path_finder;
mod process;
mod visualization;
mod scene;
mod map_db;
mod sqlite_map_db;
